version: "3"
services:
  package:
    container_name: start-repo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mypackage:/
      # edit volume
volumes:
  mypackage:
    external: true

